# -*- coding: utf-8 -*-
# 一次性脚本：把 sprite-templates.ts 的 TEMPLATES 块替换为国风版本，并追加坐骑/建筑模板。
import io, re, sys

P = 'src/render/sprite-templates.ts'
src = io.open(P, encoding='utf-8').read()

NEW_TEMPLATES = u'''export const TEMPLATES: Record<SubClass, string[]> = {
  // 玄武前排：凤翅兜鍪 + 红缨 + 兽面大橹盾 + 铁锏。
  // 剪影锚点是「左侧一块 6px 宽的方盾 + 头顶两片外翘凤翅」——远看就知道这是中式重甲将。
  physTank: [
    '....................',
    '.........gg.........',
    '........OggO........',
    '.......OOggOO.......',
    '......OmmmmmmO......',
    '.....OmOmmmmOmO.....',
    '.....OOsssssOO......',
    '.....OsSeSSeSO......',
    '.....OOsssssOO......',
    '.OOOOO.OOaaaOO.OMO..',
    'ObbbbO.OaaaaaO.OMO..',
    'ObmMmbOaabbbaaOMMMO.',
    'ObMOMbOaabbbaaOMMMO.',
    'ObmMmbOaaaaaaaOMMMO.',
    'ObbbbO.OllllllO.OMO.',
    '.OOOOO.OaaaaaaO.....',
    '.......O##O.O##O....',
    '.......O##O.O##O....',
    '......OMMMO.OMMMO...',
    '......OOOOO.OOOOO...',
  ],
  // 符甲战将：莲花道冠 + 头顶三道悬浮符箓 + 及地符纹重袍。
  // 三张竖符箓是全场唯一「一排三个等距发光块」的头顶特征，与玄武的凤翅完全不撞。
  magicTank: [
    '.....OgO.OgO.OgO....',
    '.....OwO.OwO.OwO....',
    '.....OgO.OgO.OgO....',
    '.......OObbOO.......',
    '......ObbbbbbO......',
    '.....ObbwwwwbbO.....',
    '.....OOsssssssO.....',
    '.....OsSeSSSeSO.....',
    '.....OOsssssssO.....',
    '....OOaaaaaaaaaOO...',
    '...ObaaabbbbbaaabO..',
    '..OgbaabbwwbbaabgO..',
    '..OObaaabbbbbaaabOO.',
    '...ObaaaaaaaaaaabO..',
    '...OaaaaaaaaaaaaaO..',
    '...OaaaabbbbbaaaaO..',
    '..OaaaaaaaaaaaaaaaO.',
    '..OllllllllllllllO..',
    '...O##OO....OO##O...',
    '...OOOO......OOOO...',
  ],
  // 武圣突袭（关羽）：幞头 + 五绺长髯 + 青龙偃月刀。
  // 长柄大刀从右上贯到腰际，刀头是全场唯一的「新月形金属块」；长髯给了它唯一的下颌轮廓。
  charge: [
    '..............OmmO..',
    '.............OmmmO..',
    '....OOOO....OmmMO...',
    '...ObbbbO..OmmMO....',
    '...ObwwbO.OMMO......',
    '...OsssssO.OMO......',
    '...OsSeSeO.OMO......',
    '...OOsssOO.OMO......',
    '..OObSSSbOOMO.......',
    '.OMaaSSSaaOllO......',
    '.OMaaabbbaaaO.......',
    '.OMaaabbbaaaO.......',
    '..OaaaaaaaaO........',
    '..OllllllllO........',
    '..OaaaaaaaO.........',
    '..O##O.O##O.........',
    '.O##O..O##O.........',
    'O##O....O##O........',
    'OOO......OOO........',
    '....................',
  ],
  // 无名剑客：斗笠 + 长衫 + 右侧竖直长剑 + 剑穗。
  // 斗笠檐只有 12px（比太极宗师窄），加上剑穗那一点发光，是「江湖客」而非「术士」。
  hexblade: [
    '....................',
    '.........OO.........',
    '........OwwO........',
    '.......OwwwwO.......',
    '....OOwwwwwwwwOO....',
    '....OOOOOOOOOOOO....',
    '.......OssssO.......',
    '.......OeSSeO...OmO.',
    '.......OssssO...OmO.',
    '.....OOaaaaaaOO.OmO.',
    '....OaaabbbbaaaOOmO.',
    '....OaabbwwbbaaOOmO.',
    '....OaaabbbbaaaOOMO.',
    '.....OaaaaaaaaO.OlO.',
    '.....OllllllllO.Og..',
    '.....OaaaaaaaaO.....',
    '.....OaaaaaaaO......',
    '....O##O..O##O......',
    '...O##O....O##O.....',
    '...OOO......OOO.....',
  ],
  // 神机炮手：明制笠盔 + 三眼铳。
  // 铳管是横向 6px 实心块 + 火门两点火星，是全场唯一「水平伸出体外的机械结构」。
  gunner: [
    '....................',
    '.........OO.........',
    '.....OOOOmmOOOO.....',
    '....OmmmmmmmmmmO....',
    '.....OOMMMMMMOO.....',
    '.....OsSeeSsO.......',
    '.....OOsssOO........',
    '....OOaaaaaOO.......',
    '...OMaaaaaaaMO......',
    '..OMMaabbbaaMMOOOOO.',
    '..OMMaabbbaaMMmMmMMO',
    '..OMMaaaaaaaMMmMmMMO',
    '...OMaaaaaaaMOOOOgg.',
    '...OllllllllO.......',
    '...OaaaaaaaaO.......',
    '...OaaaaaaaO........',
    '...O##O.O##O........',
    '..OMMO..OMMO........',
    '..OOOO..OOOO........',
    '....................',
  ],
  // 神射手·后羿：中式反曲长弓（两端弓梢外翻）+ 束发簪 + 右背箭袋。
  // 18px 高的竖弓 + 上下两个反曲弯钩，站桩感与射程一起从剪影读出来。
  sniper: [
    '..OO................',
    '.Om.................',
    'Om......OOOO........',
    'Om.....OaaaaO.......',
    '.Om...ObwwwwbO......',
    '.Om...OOsssOO.......',
    '.Om...OsSeeSO.......',
    'Og....OOsssOO...Ol..',
    '.Om..OOaaaaaOO..Oll.',
    '.Om..OaabbbaaO..Oll.',
    '.Om..OaabbbaaO.Oll..',
    '.Om...OaaaaaO.Oll...',
    'Om....OllllllO......',
    'Om....OaaaaaaO......',
    '.Om...OaaaaaO.......',
    '.Om...O##O##O.......',
    '..Om..O##.O##O......',
    '..OO..OMMO.OMMO.....',
    '......OOOO.OOOO.....',
    '....................',
  ],
  // 太极宗师：道髻 + 道袍 + 右侧悬浮太极盘。
  // 上窄下阔的钟形道袍 + 白色袍摆 + 一枚 4×4 阴阳鱼圆盘，与符甲战将的符箓头顶正交。
  controller: [
    '....................',
    '.......OO...........',
    '......ObbO..........',
    '.......OO...........',
    '.....OOssssOO.......',
    '.....OsSeeSsO...OOO.',
    '.....OOssssOO..OwwgO',
    '....OOaaaaaaOO.OwggO',
    '...OaaaabbaaaaO.OOO.',
    '...OaaaabgwbaaaO....',
    '...OaaabbwgbbaaaO...',
    '...OaaaabbbbaaaO....',
    '...OaaaaaaaaaaaO....',
    '..OaaaaaaaaaaaaaO...',
    '..OaaaabbbbbaaaaO...',
    '..OaaaaaaaaaaaaaO...',
    '.OaaaaaaaaaaaaaaaO..',
    '.OllllllllllllllllO.',
    '..OwwwwwwwwwwwwwO...',
    '..OOOOOOOOOOOOOOO...',
  ],
  // 女娲造人：人首蛇身。上身人形托泥丸，下身盘尾拖到画面底边。
  // 「没有腿」是它最狠的辨识点——全场唯一一个下半身是连续曲面的单位。
  summoner: [
    '....................',
    '.......OOOOO........',
    '......ObbbbbO.......',
    '.....ObbwwwbbO......',
    '.....ObOsssObO......',
    '.....ObOeSeObO......',
    '.....ObOsssObO......',
    '....OObbaaabbOO.....',
    '...ObaaaaaaaaabO....',
    '..ObaaaabgbaaaabO...',
    '..ObaaaabbbaaaabO...',
    '...ObaaaaaaaaabO....',
    '....OOaaaaaaaOO.....',
    '...ObbbaabbaabbO....',
    '..ObbbaabbbaabbbO...',
    '.ObbbbaabbbaabbbbO..',
    'ObbbbbaabbbaabbbbbO.',
    'OObbbbbbbbbbbbbbbOO.',
    '.OObbbbbbbbbbbbbOO..',
    '..OOOOOOOOOOOOOOO...',
  ],
  // 青囊神医（华佗）：儒巾 + 长须 + 右手药葫芦 + 腰间青囊。
  // 葫芦是唯一悬在体侧的「双球轮廓」，配长须与白袍摆，一眼是郎中不是法师。
  healer: [
    '....................',
    '.......OOOOO........',
    '......OwwwwwO.......',
    '......OwOOOwO.......',
    '.....OOsssssO..Og...',
    '.....OsSeeSsO.OgwgO.',
    '.....OOsssssO.OggwO.',
    '.....OSSSSSO...OO...',
    '....OOaSSSaOO.......',
    '...OaaawwaaaO..OmO..',
    '...OaawwwwaaO..OmO..',
    '...OaaawwaaaO.OmO...',
    '...OaaaaaaaaO.......',
    '..ObaagaaaaabO......',
    '..OaaaaaaaaaaO......',
    '..OaaaabbbaaaO......',
    '.OaaaaaaaaaaaaO.....',
    '.OaaaaaaaaaaaaO.....',
    '.OwwwwwwwwwwwwO.....',
    '..OOOOOOOOOOOO......',
  ],
};'''

# ── 替换 TEMPLATES 块 ────────────────────────────────────────────
start = src.index('export const TEMPLATES: Record<SubClass, string[]> = {')
end = src.index('\n// \u2500\u2500 \u53ec\u5524\u7269\u6a21\u677f', start)
src = src[:start] + NEW_TEMPLATES + '\n' + src[end + 1:]

io.open(P, 'w', encoding='utf-8', newline='\n').write(src)
print('TEMPLATES replaced, file len =', len(src))
